# Generated by Django 4.0.4 on 2022-06-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('pk',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shortdesc',
            new_name='short_desc',
        ),
    ]
